library(readxl)
library(dplyr)
library(stringr)
library(tibble)
library(tidyr)
library(rgdal)
library(geojsonio)
devtools::load_all()

print("---------Process cells-------------")
source("vignettes/import/cells.R")
print("-------------Process vegetations-------------")
source("vignettes/import/vegetation.R")
print("-------------Process papillons-------------")
source("vignettes/import/papillon.R")
print("-------------Process microfaunes - carabes-------------")
source("vignettes/import/insectes_sol.R")
print("-------------Process odonates-------------")
source("vignettes/import/odonate.R")
print("-------------Process mammifères-------------")
source("vignettes/import/mammiferes.R")
